name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read versions from gradle.properties
        id: get_versions
        run: |
          PROJECT_VERSION=$(grep 'projectVersion' gradle.properties | cut -d'=' -f2)
          TELEGRAM_VERSION=$(grep 'telegrambotsVersion' gradle.properties | cut -d'=' -f2)
          TAG_NAME="v${PROJECT_VERSION}-${TELEGRAM_VERSION}"
          echo "Generated tag name: $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create and Push Tag
        id: create_tag
        run: |
          TAG_NAME="${{ steps.get_versions.outputs.TAG_NAME }}"
          echo "Attempting to create and push tag: $TAG_NAME"
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping tag creation."
          else
            git tag $TAG_NAME
            git push origin $TAG_NAME
            echo "Successfully created and pushed tag $TAG_NAME."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Generate Release Notes
        id: generate_release_notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          tag: ${{ steps.get_versions.outputs.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.get_versions.outputs.TAG_NAME }}
          name: Release ${{ steps.get_versions.outputs.TAG_NAME }}
          body: ${{ steps.generate_release_notes.outputs.body }}
          make_latest: true
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
